submit_application = "📝 Ariza yuborish"
send_message_to_admin_text = "📝 Adminga xabar yuborish"
add_group = "Guruh qo'shish"
add_course = "Yangi kurs ochish"
find_user = "Foydalanuvchini qidirish"
list_group = "Guruhlar ro'yhati"
list_course = "Kurslar ro'yhati"
