submit_application = "📝 Ariza yuborish"
terms = "Qatnashish uchun bizni shartlarimiz:\n\n1-shart: ...\n2-shart ...\n3-shart ..."
send_message_to_admin_text = "📝 Adminga xabar yuborish"
add_group = "Guruh qo'shish"
add_course = "Yangi kurs ochish"
find_user = "Foydalanuvchini qidirish"
